### ISSUE TITLE
iOS - get returns empty object

### ISSUE THREAD

**Issue by brantleyenglish** [react-native-community/cookies#53]
I have tried get() with specific examples with and without the useWebKit variable.
Each time, CookieManager has returned as an empty object, and no errors have been created. 
Built on react native init. No expo.

For example:
```
import CookieManager from '@react-native-community/cookies';

...
const getCookies = async () => {
  const useWebKit = true;
  try {
    const cookies = await CookieManager.getAll(useWebKit);
    console.log({cookies});
  } catch (error) {
    console.log({error});
  }
};
```
returns `{"cookies": {}}` in the console

I am using iOS ver 13.5.
In package.json:
"@react-native-community/cookies": "^2.0.9",
"react-native-wkwebview-reborn": "^2.0.0",

**Comment by Miluaaa** [comment]
Did you solve it？

**Comment by vlerant-saiti** [comment]
Did you find any solution?

**Comment by Miluaaa** [comment]
> Did you find any solution?

After logging in, close the application and enter again. Does the login state remain?

After logging in to the application, close the application by killing the process. Open the application again and expect the login status to remain. What is the actual effect?

If the login interface returns a cookie, an expiration time is set for the cookie value, and the expiration time is after the current time, that is, it has not expired. Then enter the application again, the cookie value remains. Both ios and android are valid

If the login interface returns a cookie, the cookie value is not set with an expiration time, or a time before the current time is set. When entering the application again, the cookie value on the ios side is lost, but the value on the android side remains

Therefore, in order to remain logged in when entering the application again. When setting the cookie token on the login interface, a relatively long expiration time needs to be set.

**Comment by vlerant-saiti** [comment]
> > Did you find any solution?
> 
> After logging in, close the application and enter again. Does the login state remain?
> 
> After logging in to the application, close the application by killing the process. Open the application again and expect the login status to remain. What is the actual effect?
> 
> If the login interface returns a cookie, an expiration time is set for the cookie value, and the expiration time is after the current time, that is, it has not expired. Then enter the application again, the cookie value remains. Both ios and android are valid
> 
> If the login interface returns a cookie, the cookie value is not set with an expiration time, or a time before the current time is set. When entering the application again, the cookie value on the ios side is lost, but the value on the android side remains
> 
> Therefore, in order to remain logged in when entering the application again. When setting the cookie token on the login interface, a relatively long expiration time needs to be set.

I am trying to save Instagram cookies after user logins from webview. 

Do you think thats possible?

**Comment by safaiyeh** [comment]
@vlerant-saiti the best way would to store the cookie in storage and set the cookie before you make the request. Would this work for you?

**Comment by vlerant-saiti** [comment]
> @vlerant-saiti the best way would to store the cookie in storage and set the cookie before you make the request. Would this work for you?

Thats what I did. It worked

**Comment by safaiyeh** [comment]
Awesome @brantleyenglish I wil close this issue for now as cookies is now v4, if the same issue occurs feel free to reopen

**Comment by vlerant-saiti** [comment]
> @vlerant-saiti the best way would to store the cookie in storage and set the cookie before you make the request. Would this work for you?

For some reason, I am not able to get cookies. Now I get empty object after user logins.

**Comment by safaiyeh** [comment]
@vlerant-saiti can you provide a reproducible repo?

**Comment by Willyfp** [comment]
I had the same problem this week, in my case, I was setting an expiration with Dayjs and this caused the problem. Using the vanilla Date API fixed the issue.
